### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#1]
Neues Icon + neue Buttons, etc. (gelb) lt Dropbox   CheckIn/res/...

**Comment by skienzl** [comment]
bei btn_default_register_pressed und btn_default_register is bei den 9.png was daneben gangen. die strecken sich nicht mit.

**Comment by Didi71** [comment]
ich versteh' deinen Kommentar nicht - meinst du das liegt an den Bildern?

Am 17.11.2013 21:54, schrieb skienzl:

**Comment by skienzl** [comment]
Die Bilder die auf .9.PNG enden haben dynamische bereiche die mitwachsen.
Wenn die falsch gemacht sind dann verzehrt das Bild. Bei den beiden ist
anscheinend was daneben gegangen.
Am 17.11.2013 23:05 schrieb "Didi71" notifications@github.com:

**Comment by Didi71** [comment]
ok - schau ich mir an - ich dachte das wären ganz normale pixel - pngs

Am 17.11.2013 23:07, schrieb skienzl:

**Comment by Didi71** [comment]
Hab' neue Bilder in die Dropbox geladen - bin mir net sicher ob's jetzt 
geht, aber versuch's mal bitte.

Am 17.11.2013 23:07, schrieb skienzl:
