### ISSUE TITLE
CheckIn - CheckPoint nicht aktiviert

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#10]
Wenn man bei einem CheckPoint eincheckt der noch nicht aktiviert ist, dann gibt' die App zusätzlich zur Message die checkInV2-Test.php zurückgibt auch noch die Fehlermeldung: "Netzwerk Fehler" aus.

Es sollte nur die Meldung ausgegeben werden die vom Server zurückgegeben wird.

Die einzige Meldung die die App ausgibt ist, wenn keine Internetverbindung zur Verfügung steht.

**Comment by skienzl** [comment]
was ist mit den std fehler code meldungen? sollen die noch ausgegeben werden?

**Comment by Didi71** [comment]
nein - die brauchen wir eigentlich auch nicht mehr. 
die Fehlermeldungen (bei checkInV2.php, getFacts.php und checkInV2.php liefere ich zurück - mit Ausnahme, dass keine Internetverbindung zur Verfügung steht.
