### ISSUE TITLE
Bikebird in der Headline

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#12]
Der BIKEbird in der Headline sollte schwarz sein - ich find nur leider das entsprechende Icon nicht.

**Comment by skienzl** [comment]
sagst halt wenn es hast

**Comment by Didi71** [comment]
ich find' den derzeitigen weissen Bikebird nicht - kannst du mir sagen wo du den her nimmst, damit ich ihn schwärzen kann.

**Comment by skienzl** [comment]
ic_launcher_ab.png. ist auf der dropbox im ordern android-> res -> und dann in den jeweiligen foldern 

Am 25.11.2013 um 11:53 schrieb Didi71 notifications@github.com:

> ich find' den derzeitigen weissen Bikebird nicht - kannst du mir sagen wo du den her nimmst, damit ich ihn schwärzen kann.
> 
> —
> Reply to this email directly or view it on GitHub.

Stefan Kienzl
http://skienzl.com/

**Comment by Didi71** [comment]
sind jetzt unter CheckIn/adroid/res ... verfügbar.

Am 25.11.2013 11:56, schrieb skienzl:
