### ISSUE TITLE
checkInV2-Test.php TableCircle2Row

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#14]
Die App ignoriert folgende Screens beim Aufruf von checkInV2-Test.php:

TableCircle2Row
Table3Row

**Comment by Didi71** [comment]
ist testbar, wenn man bei CP14672002 eincheckt.

**Comment by skienzl** [comment]
das sind sie auch nicht bei der bikeline ;) war dort auch nie ausgemacht didi

**Comment by Didi71** [comment]
wir hatten doch gesagt, dass alle Screentypen sowohl bei checkInV2 als 
auch bei getFacts.php anzeigbar sein sollen - oder täusch ich mich?
wir haben damals ja auch die ganzen Circle Screens bei getFacts.php 
eingefügt.

Am 25.11.2013 17:31, schrieb skienzl:

**Comment by skienzl** [comment]
dort schon. aber nicht umgekehrt.

**Comment by Didi71** [comment]
Ok - dann war das wohl ein Missverständnis.

Sollten wir nochholen, sobald wieder Knödl in der Kasse sind.
Werd' für's Erste einen anderen Screentyp nutzen.

Am 25.11.2013 17:36, schrieb skienzl:

**Comment by skienzl** [comment]
wenn i zeit hab mach ich dir das noch so.

**Comment by Didi71** [comment]
jucheee - danke!

Am 25.11.2013 17:40, schrieb skienzl:

**Comment by skienzl** [comment]
hast du den cp mit den tests wieder entfernt?

**Comment by Didi71** [comment]
was meinst du mit cp entfernt? woraus entfernt?

Am 25.11.2013 18:18, schrieb skienzl:

**Comment by skienzl** [comment]
es kommt jetzt was anders bei CP14672002

**Comment by Didi71** [comment]
jetzt sollte es wieder drin sein.

Am 25.11.2013 18:45, schrieb skienzl:

**Comment by skienzl** [comment]
leider immer noch der vogel mit der fassadendämmung :)

**Comment by Didi71** [comment]
jetzt aber - sorry war kurz weg.

Am 25.11.2013 18:53, schrieb skienzl:
