### ISSUE TITLE
Facts -> Links in TableCircle2Row

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#16]
Check mal bitte bei CP14672002 ein.

Wähle dann BIKEbirds im Hauptmenü, danach Spiele und Kaindorfer Ökopfad.
Da erscheint dann eine Liste mit allen CheckPoints des Ökopfades. Zumindest der CheckPoint Fassadendämmung sollte abgehakt sein.

Wenn man "Fassadendämmung" anwählt, dann sollte man mittels Link zu einer weiteren Seite kommen. Das funktioniert aber leider nicht.

**Comment by skienzl** [comment]
da kann ich mich aber sehr sehr gut erinnern das wir damals nur eine subeben von screens vereinbart haben ;) das ist einfach nicht implementiert :)

**Comment by Didi71** [comment]
ok! dann muss ich das irgendwie anders lösen!
lass ma's aber als issue (enhancement) in der Liste.

Am 26.11.2013 20:29, schrieb skienzl:
