### ISSUE TITLE
Sound stoppen

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#17]
Wenn ein Screen einen Sound abspielt, dann sollte der Sound stoppen, wenn man einen anderen Screen wählt.

**Comment by Didi71** [comment]
Wenn man zu einem Screen mit Sound wechselt, dann sollte der Screen auch wieder abgespielt werden, unabhängig davon ob der Sound dieses Screens bereits einmal gestoppt wurde.

**Comment by skienzl** [comment]
Ist das nicht ein wenig nervig für den user :)  er geht ja nicht ohne Grund
weiter. Er ist mit dem screen ja fertig und will ihn ja nicht wieder
erleben
Am 07.12.2013 20:11 schrieb "Didi71" notifications@github.com:

**Comment by Didi71** [comment]
wenn ihn der Sound nicht interessiert, dann kann er ja ohnehin gleich 
zum nächsten Screen wechseln.
wenn der Sound aber nicht mehr abgespielt wird, dann kann er sich's gar 
nicht mehr anhören.

Am 07.12.2013 20:14, schrieb skienzl:

**Comment by skienzl** [comment]
also du willst es folgend: 
1) user kommt auf screen1 und sound startet
2) user geht zu screen2 und sound stoppt 
3) user kommt zurück zu screen1 und der sound  soll weiter gehen

**Comment by Didi71** [comment]
ja. Sobald man einen Screen besucht startet der Sound dieses neuen Screens.
Wenn man einen Screen verlässt, stoppt der Sound des verlassenen 
Screens, und es beginnt der Sound des neuen Screens (falls der einen hat.)

Am 07.12.2013 20:20, schrieb skienzl:

**Comment by skienzl** [comment]
aber das der sound wieder weiter machen soll bzw neu anfangen finde ich zu viel. ich denke das würde sehr schnell den meisten usern zu viel werden.

**Comment by Didi71** [comment]
wir planen hier gemeinsam mit der Volksschule einen Lehrpfad, bei dem 
Volksschulkinder, wenn man bei einem CheckPoint einchecken zu diesem 
CheckPoint (z.B. Fotovoltaik) was erzählen. Und diese Erzählungen 
sollten sich die Einchecker (Eltern, Bekannte und Verwandte) nochmals 
anhören können.

Für die üblichen Soundeffekte magst du recht haben, da dürfte es bald 
mal "nervig" werden, aber für die Erzählungen der Kids brauchen wir das.

Am 07.12.2013 20:29, schrieb skienzl:

**Comment by skienzl** [comment]
wenn die dateien groß werden wird das spannend ob die so schnell geladen werden.

**Comment by Didi71** [comment]
ja - ist aber nur gesprochener Text, da können wir mit der Samplerate 
ziemlich weit runter gehen und mehr als 20-30 Sekunden werdens ohnehin 
nicht sein.

Am 07.12.2013 20:37, schrieb skienzl:

**Comment by skienzl** [comment]
wie du meinst :) dann werd ich das in den nächsten tagen einmal checken :)

**Comment by skienzl** [comment]
bei qr code werden mehrere sounds abgespielt?

**Comment by Didi71** [comment]
Die sounds hängen an den Screens.
Wenn mehrere Screens mit Sounds geliefert werden, dann sind auch mehrere 
Sounds abzuspielen.

Am 11.12.2013 13:41, schrieb skienzl:

**Comment by skienzl** [comment]
das ist mir klar. ich brauche aber testbeispiele. habe mich oben falsch ausgedrückt.

**Comment by Didi71** [comment]
Checkpoint 14672002 und z.B. Cp 14672011. 

Am 12.12.2013 um 10:52 schrieb skienzl notifications@github.com:

**Comment by Didi71** [comment]
wenn man zum Screen mit Sound wechselt, dann sollte der Sound immer von Beginn an abgespielt werden
