### ISSUE TITLE
Info Screen - Textgröße

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#18]
Die Textgröße am Info - Screen sollte gleich sein, wie die Textgrößen der anderen Screens.

**Comment by skienzl** [comment]
und welche textgröße von den anderen screens?

**Comment by Didi71** [comment]
die derzeitige <big> Größe sollte die normale Größe sein.

kann man da eigentlich auch Bilder anzeigen bzw. den Text zentrieren?

Am 26.11.2013 20:03, schrieb skienzl:

**Comment by skienzl** [comment]
keine ahnung ob bilder anzeigen gehen. müsstest probieren.
