### ISSUE TITLE
Schriftfarbe in Messages (Nexus)

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#20]
Sowohl der Hintergrund als auch die Schriftfarbe in Messages & Toasts sind schwarz, Schriftfarbe bitte auf weiß ändern.

**Comment by skienzl** [comment]
lade gerade eine neue version auf testflight. bitte beides testen.

**Comment by Didi71** [comment]
beim Samsung geht's beim Nexus noch nicht!
