### ISSUE TITLE
bikebirds / group-icons Hintergrund (Nexus)

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#23]
Bei den GroupIcons ist der Hintergrund bei der BIKEline App transparent. Das sollte er auch bei der CheckIn App sein.

**Comment by skienzl** [comment]
die tabicons bei den facts?

**Comment by Didi71** [comment]
jo

**Comment by skienzl** [comment]
bei is der transparent. kannst mir einen screenshots schicken. bzw bei welchen device

**Comment by Didi71** [comment]
![screen19](https://f.cloud.github.com/assets/5090129/1698530/91d80da0-5f53-11e3-93b3-21780d5ff290.jpg)

**Comment by skienzl** [comment]
ist das bei allen devices so?

**Comment by Didi71** [comment]
grad gschaut! beim Samsung Galaxy geht's. Nicht funkts beim Nexus.

Am 07.12.2013 16:38, schrieb skienzl:

**Comment by skienzl** [comment]
aber bei der bikeline passt es beim nexus?

**Comment by Didi71** [comment]
ja!

Am 07.12.2013 16:42, schrieb skienzl:

**Comment by skienzl** [comment]
sorry. keine ahnung warum das nexus da die transparenz nicht annehmen will.

**Comment by Didi71** [comment]
group icon Hintergrund funktioniert jetzt, aber beim Actionbar-Hintergrund hakt's noch.
![screen22](https://f.cloud.github.com/assets/5090129/1736910/5578ab88-636a-11e3-8521-51dc1abceabb.jpg)

**Comment by skienzl** [comment]
ist das bei allen screens?

**Comment by Didi71** [comment]
ja

**Comment by skienzl** [comment]
ist das erst mit dieser version gekommen oder ist das schon länger das die actionbar schwarz ist?

**Comment by Didi71** [comment]
das ist seit du den GroupIcon Hintergrund auf transparent geändert hast

Am 16.12.2013 18:15, schrieb skienzl:
