### ISSUE TITLE
getFacts -> ScreenIds

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#24]
Beim Aufruf von getFacts.php werden von der App. keine ScreenIds mitgeschickt.

**Comment by Didi71** [comment]
die ScreenIds Liste sollte die Ids allers Screens (inkl. SubScreens, und SubSubScreens) beinhalten, damit auch Subscreens gezielt erweitert, gelöscht, etc. werden können.

**Comment by skienzl** [comment]
aber mit den timestamps und den ids weist du e wer was wann bekommen hat. ich hab die objekte nämlich nur als blobs und müsst da dann alle durchgehen.

**Comment by Didi71** [comment]
ich speichere aber nicht, wer wann was bekommen hat. Wenn ich es mir 
aufgrund des Zeitstempels dann nochmals "berechne", dann muss ich zwei 
Berechnungen durchführen. Eine für den "alten" Timestamp, und eine für 
den aktuellen Timestamp. Dann muss ich mir die Differenz aus beiden 
bilden, und ...
Des is scho a bissl kompliziert und ein Zeitfresser am Server.

Besser wäre sicherlich, wenn die App sich merkt, welche Screens bei 
getFacts angezeigt werden (das muss sie ja, denk' ich, ohnehin irgendwie 
machen, denn wie weiss die App sonst welche Screens im Falle KEINER 
Internetverbindung anzuzeigen sind), und die App dem Server dann 
mitteilt, welche Screens sie aktuell anzeigt.

Am 11.12.2013 13:10, schrieb skienzl:

**Comment by skienzl** [comment]
ja sicher speichere ich mir das. aber nur den json body als blob des ersten screens. das heißt ich müsste immer alles generieren weil wir ja ausgemacht haben das sich wenn sich was ändert immer der ganze erste screen ausgetauscht wird inkl seiner unterscreens damit ich nicht checken muss was sich geändert hat. das hatten wir so besprochen.

**Comment by Didi71** [comment]
Hmm! was ist dann der Unterschied zwischen "new" und "update". Ich hatte 
eigentlich angedacht, dass bei "new" der Screen komplett neu angelegt 
wird, d.h. alle seine bisherigen Daten verworfen werden, und bei 
"update" die bisherigen Daten erhalten bleiben und etwaige neue Daten 
(z.B. weitere Einträge in einer Tabelle) angehängt werden. Und "delete" 
löscht einen Screen (auch Subscreen).

Wie dem auch sei, lass uns das Prozedere nun abkürzen.

Wenn ich dich richtig verstanden hab, dann ist folgendes implementiert, 
und das gilt immer für den ersten Screen, die Subscreens laufen quasi 
mit den ersten Screens mit.

"delete" löscht einen Screen.
"update" verwirft alle Daten des Screens und legt ihn neu an.
"new" ... wenn der Screen neu dazu kommt, d.h. in der screenId Liste 
nicht vorkommt

Richtig?

Am 12.12.2013 10:52, schrieb skienzl:

**Comment by skienzl** [comment]
genau so ist es

**Comment by Didi71** [comment]
Passt, dann werd ich den Server anpassen.

Am 12.12.2013 um 11:05 schrieb skienzl notifications@github.com:
