### ISSUE TITLE
Facts - tabicons - Strich drunter

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#26]
Die Farbe des Striches unter den Tabicons sollte schwarz sein. Derzeit wird sie weiß dargestellt, sollte aber, da sich die Textfarbe von weiß (BIKEline) auf schwarz (CheckIn) geändert hat, auch schwarz angezeigt werden.

![screen19](https://f.cloud.github.com/assets/5090129/1698590/14702ace-5f57-11e3-9b40-a4d4463c9a4d.jpg)

**Comment by skienzl** [comment]
da musst du mir wieder die resources ändenr. alle tab_ in schwarz färben. sind wieder 0.png. also aufpassen

**Comment by Didi71** [comment]
hab' die beiden Files: textfield_default.png und 
textfield_activated.9.png aktualisiert.

Am 07.12.2013 16:52, schrieb skienzl:

**Comment by skienzl** [comment]
die mit "tab_" beginnen. nicht die "textfield"!!!

**Comment by Didi71** [comment]
oha da muss ich in's andere Verzeichnis - wofür sind die textfield ...
brauchen wir die auch dunkel?

Am 07.12.2013 17:06, schrieb skienzl:

**Comment by skienzl** [comment]
das sind die eingabefelder. der weiße (jetzt schwarze) strich der es unterstreicht. siehst wenn du auf profil bearbeiten gehst.

**Comment by Didi71** [comment]
tabs in tab_bar sind jetzt aktualisiert.

Am 07.12.2013 17:06, schrieb skienzl:

**Comment by Didi71** [comment]
Ok. Den lassma jetzt auch mal schwarz.

Am 07.12.2013 um 17:11 schrieb skienzl notifications@github.com:
