### ISSUE TITLE
Screen new

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#27]
Auch wenn alle Screens als "new" angegeben werden und somit neu aufgebaut werden sollten, werden nicht alle SubScreens aktualisiert und neu angelegt.

**Comment by Didi71** [comment]
Ich geb' bei getFacts jetzt bei der Fassadendämmung die aktuelle Uhrzeit aus - damit solltest du es testen können.

**Comment by skienzl** [comment]
welche getFacts genau?

**Comment by skienzl** [comment]
und die operation für update ist nicht "new" sondern "update". die haben wir gesagt wenden wir nur auf der erste screen ebene an.

**Comment by Didi71** [comment]
ja, aber wenn ich einen Screen als "new" zurückgeben, dann sollte alle bisherigen Infos dieses Screen in der App gelöscht werden.

**Comment by skienzl** [comment]
und was sollte dann der untreschied zu update sein. dort werden die inhalte ja auch ersetzt.
