### ISSUE TITLE
Farbfehler

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#28]
![screenshot_2013-12-12-21-59-45 1](https://f.cloud.github.com/assets/5090129/1737288/95f9d884-6370-11e3-8197-fa80d45eb378.png)

![screenshot_2013-12-12-22-02-36 1](https://f.cloud.github.com/assets/5090129/1737292/c8223888-6370-11e3-823d-29b12c5c422c.png)

![screenshot_2013-12-12-22-03-07 1](https://f.cloud.github.com/assets/5090129/1737297/e7fd127c-6370-11e3-8aee-d0fbba47e137.png)

Bitte Überschrift: "Profilbild aufnehmen"
Rand wenn geht auch gelb!
![screenshot_2013-12-12-22-03-26 1](https://f.cloud.github.com/assets/5090129/1737299/f5437746-6370-11e3-83ca-2df67bda7086.png)

Wenn du diesen Screen nach links oder rechts ziehst, dann wird der Rand türkis
![screenshot_2013-12-12-22-05-46 1](https://f.cloud.github.com/assets/5090129/1737310/385e0c94-6371-11e3-9f69-8418e810ac2d.png)

![screenshot_2013-12-12-22-06-25 1](https://f.cloud.github.com/assets/5090129/1737319/4d2a5cea-6371-11e3-913e-279f5750b00f.png)

Cursor blinkt türkis statt schwarz oder grau
![screenshot_2013-12-12-22-09-29 1](https://f.cloud.github.com/assets/5090129/1737360/bcafae08-6371-11e3-8f86-8cd397719a09.png)

Gilt für +, - und den Homebutton und den Backbutton
![screenshot_2013-12-12-22-10-45 1](https://f.cloud.github.com/assets/5090129/1737373/ea6cea36-6371-11e3-8c93-1a16d48f9a3c.png)

Wenn man auf das InfoFenster tippt, wird es türkis
![screenshot_2013-12-12-22-50-10 1](https://f.cloud.github.com/assets/5090129/1737696/7502d840-6377-11e3-831d-518cfc17d839.png)

**Comment by skienzl** [comment]
hab soweit es möglich ist die farben behoben. leider sind einige farben nicht veränderbar (map und menu). das türkis ist nämlich die standard farbe von android.
