### ISSUE TITLE
getFacts.php ???

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#32]
Wenn ich jetzt die Facts anzeigen will, dann passiert nix. Die App steckt.
Hast du eine Ahnung woran's liegen könnte?

![screenshot_2013-12-20-14-05-34 1](https://f.cloud.github.com/assets/5090129/1790500/97291474-6977-11e3-9b72-cf7653f28925.png)

**Comment by skienzl** [comment]
vl weil du die app neu installiert hast und gleich ein "update" schickst statt einem "new". und wenn die app neu installiert ist kann er nix updaten.

**Comment by Didi71** [comment]
lag am Skript
