### ISSUE TITLE
Message: keine Internet verfügbar - Textfarbe weiss

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#33]
Bei der Message, dass z.B. das Internet nicht verfügbar ist, ist die Textfarbe Weiss.
Außerdem sollte in diesem Fall folgende Nachricht ausgegeben werde.

Head: keine Internetverbindung
Body: Derzeit besteht keine Internetverbindung. Die angezeigten Daten sind deshalb möglicherweise veraltet.

Die Daten sollten dann aber trotzdem angezeigt werden.

![screenshot_2013-12-20-14-03-22 1](https://f.cloud.github.com/assets/5090129/1790506/d57e946a-6977-11e3-80cf-7f4422b8e57b.png)

**Comment by skienzl** [comment]
vl noch keine daten da zum anzeigen?

**Comment by Didi71** [comment]
Ja, aber da geht's darum, dass der Infotext weiß und falsch ist.

Am 20.12.2013 um 14:19 schrieb skienzl notifications@github.com:

**Comment by skienzl** [comment]
meien antwort ist auch auf "Die Daten sollten dann aber trotzdem angezeigt werden." bezogen :)

**Comment by Didi71** [comment]
Oha. In diesem Fall wär's besser die Meldung: Header: keine Internetverbinfung, Body: Keine Infos verfügbar

Anzuzeigen.

Wenn auf den Server zugegriffen werden kann, dann schick ich immer Daten Retour.

Am 20.12.2013 um 14:39 schrieb skienzl notifications@github.com:
