### ISSUE TITLE
CheckIn -> CHECKin

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#34]
Bitte den Namen der App umbenennen in CHECKin

**Comment by Didi71** [comment]
App heißt jetzt offensichtlich wieder CheckIn -> sollte aber CHECKin heißen.

**Comment by Didi71** [comment]
Jetzt kenn ich mir gar nicht mehr aus. Hab' grad die CHECKin Version 1.5 (6) #11 installiert.
Jetzt heisst die App wieder CheckIn, aber was noch viel verwirrender ist, ist dass wenn ich mir die Facts anschaunen will, in der Action "CheckIn & Preise" angezeigt wird.  ???

![screen22](https://f.cloud.github.com/assets/5090129/1965660/14e7e9a4-82bd-11e3-9a93-f2114a1b4800.jpg)

**Comment by skienzl** [comment]
ich hab nirgends mehr den string im app und seh auch nirgends das problem bei mir

**Comment by Didi71** [comment]
nachdem ich die alte App. komplett deinstalliert und die neue 
installiert hatte.
gehts.

Am 11.02.2014 10:27, schrieb skienzl:
