### ISSUE TITLE
Hauptmenü - Farbe

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#37]
Wenn man in Hauptmenu z.B. auf "Allgemeine Infos" tippt, dann ist die Focusfarbe türkis - sollte aber gelb sein

**Comment by skienzl** [comment]
das haben wir schon einmal geschaut. hab aber keine gescheide lösung gefunden. das ist leider android standard.

**Comment by Didi71** [comment]
sorry - das hatte ich vergessen!

Am 21.01.2014 11:40, schrieb skienzl:
