### ISSUE TITLE
ActionBar Farbe - CheckIn-App

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#39]
Die Farbe der ActionBar bei CheckIn ist schwarz. Bei BIKEline funktionert's.

![screen08](https://f.cloud.github.com/assets/5090129/1965100/2f757284-82b6-11e3-955e-14adddc1272f.jpg)
![screen07](https://f.cloud.github.com/assets/5090129/1965101/2f77ad10-82b6-11e3-96a3-0e71e3d0bfad.jpg)

**Comment by skienzl** [comment]
lass mich raten. beim nexus one?

**Comment by Didi71** [comment]
ich glaub' das hänge eher von Android 2.3 ab, weil auf meinen Odys Tablet hab ich das Problem auch

**Comment by Didi71** [comment]
interessant ist, dass es nur bei CheckIn auftritt und nicht bei der BIKEline App
