### ISSUE TITLE
Skript-Pfad

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#4]
der Pfad für die Skripte lautet:

www.bikebird.at/CheckIn/TestApp-Scripts

**Comment by skienzl** [comment]
hab die app jetzt einmal versucht zu kopieren wie für die 250 vereinbart. leider kommt beim server ein fehler zurück:

/CheckIn/TestApp-Scripts/registerBiker.php
<p>cannot connect to host
    <br>host: localhost
        <br>user: root{"errorCode":255}

**Comment by Didi71** [comment]
hoppla - jetzt sollte es gehen.

Am 17.11.2013 21:40, schrieb skienzl:
