### ISSUE TITLE
CheckPoint + Facts - InfoBox - Textfarbe (Nexus One)

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#40]
Textfarbe der Infobox (bei allen Screens) ist offensichtlich schwarz

![screen15](https://f.cloud.github.com/assets/5090129/1965158/be234510-82b6-11e3-83a7-2d8a8265e5ca.jpg)

**Comment by skienzl** [comment]
so würde das ausschauen wenn der style custom ist. hab leider keine andere lösung gefunden. 

![screenshot_2014-01-21-18-31-00](https://f.cloud.github.com/assets/4992387/1965997/e4449e28-82c1-11e3-8246-51d3a50a47f2.png)

**Comment by Didi71** [comment]
passt
Am 21.01.2014 18:32, schrieb skienzl:
