### ISSUE TITLE
Hauptmenü Hintergrund transparent (Nexus One)

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#41]
Hintergrund sollte weiß sein - Schriftfarbe schwarz

![screen17](https://f.cloud.github.com/assets/5090129/1965243/c5de98ee-82b7-11e3-945f-bc5746ee0b08.jpg)

wenn man drauftippt, dann passts (schwarz auf gelb)

![screen18](https://f.cloud.github.com/assets/5090129/1965272/2e1052d6-82b8-11e3-8ac6-1121b7d8d794.jpg)

am Samsung Galaxy S3 passt's, allerdings wird's wenn man drauftippt türkis (offensichtlich Android default)

![screen19](https://f.cloud.github.com/assets/5090129/1965288/6dda5f1a-82b8-11e3-9a87-c32a7d890885.jpg)

**Comment by skienzl** [comment]
wäre es schlimm wenn die actionbar bei der checkin app keine leichte transparenz hat?

**Comment by Didi71** [comment]
naja - schöner wär's schon. ich versteh' nur nicht, warum's bei BIKEline 
funktioniert, aber bei CHECKIn nicht - und das am selben Handy.

Am 21.01.2014 18:11, schrieb skienzl:

**Comment by skienzl** [comment]
das mit der transparent hätte ich schon hinbekommen. 
aber das menü macht das problem. wenn ich die menüfarbe für diese geräte auf eine farbe änder dann betrifft das auch den bereich wo das logo + screen name liegt. der hat dann eben auch die farbe.
das mit android unter 2.3.3 macht anständig probleme da muss ich sagen

**Comment by Didi71** [comment]
aber das passt dann doch oder. Mach ma den Bereich logo + screen gelb 
und teiltransparent, und damit wird die Menüfarbe dann auch gelb - perfekt.

Am 21.01.2014 18:18, schrieb skienzl:

**Comment by skienzl** [comment]
teil transparent + teil transparent ergibt mehr transparenz. das sieht man dann auch

**Comment by Didi71** [comment]
bei der BIKEline App ist der Menühintergrund weiß (Text schwarz) und 
leicht transparent.
das könnten wir bei der CHECKin App doch genauso machen.

Am 21.01.2014 18:21, schrieb skienzl:
