### ISSUE TITLE
Homescreen - Logo

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#42]
Wäre es möglich, dass das Logo ca. 50% der Breite des HomeScreens einnimmt (wie beim Galaxy).

Bei größen Display (Odys Space) schaut's sonst nämlich uncool aus.

![screen20](https://f.cloud.github.com/assets/5090129/1965540/4d4851d2-82bb-11e3-8a95-f38d17e960f7.jpg)

**Comment by skienzl** [comment]
das heist du willst das layout wegen einem gerätes anpassen? 
dann brauche ich aber wegen dem einen gerät die grafiken größer weil das was derzeit angezeigt wird die originalgröße ist. wenn du das vergrößerst wird es verpixelt.

**Comment by Didi71** [comment]
du hast wahrscheinlich recht - es wird wohl niemand mit einem Tablett 
herumlaufen und einchecken!
lass' ma's so wie's is.

Am 21.01.2014 18:33, schrieb skienzl:
