### ISSUE TITLE
CheckIn & Preise -> steckt (Samsung Galaxy)

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#43]
Beim Samsung Galaxy hängt sich die App jetzt auf, wenn man die Facts anzeigen lassen will.

CheckIn & Preise bitte umbenennen in BIKEbirds

**Comment by skienzl** [comment]
bitte testen

**Comment by Didi71** [comment]
Problem besteht noch immer !

![screen46](https://f.cloud.github.com/assets/5090129/2134507/f1f2033c-92e6-11e3-8eb2-834c8eeec690.jpg)

**Comment by skienzl** [comment]
ist das bei allen geräten?? 
hab nämlich nix geändert und auch bei mir geht alles

**Comment by skienzl** [comment]
kannst du die app das nächste mal komplett löschen

**Comment by Didi71** [comment]
Ok mach ich

**Comment by Didi71** [comment]
Hab's mit Galaxy S3 getestet.

**Comment by Didi71** [comment]
ja, ist bei allen Geräten so

Am 11.02.2014 10:29, schrieb skienzl:

**Comment by skienzl** [comment]
stürzt die app auch ab?

**Comment by Didi71** [comment]
Nein, bleibt nur hängen.
