### ISSUE TITLE
Profil bearbeiten - Foto fehlt

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#47]
Beim Profil bearbeiten fehlt das Foto

![screen47](https://f.cloud.github.com/assets/5090129/2136011/2c6ea7aa-9309-11e3-913f-1851fe2d65b6.jpg)

**Comment by skienzl** [comment]
wann tritt das auf? wenn du dich anmeldest oder wenn du schon ein foto gemacht hast?

**Comment by Didi71** [comment]
Wenn man schon ein Foto gemacht hat.
