### ISSUE TITLE
Message Boxes (Android 2.3)

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#49]
Die Message Boxes schauen grausam aus! z.B. Lade BIKEbirds ...

**Comment by skienzl** [comment]
das hab ich dich aber damals gefragt und du hast das ok gegeben....

**Comment by Didi71** [comment]
ja, beim Samsung ist's ja ok, aber bei Android 2.3 geht der obere Teil 
der Messagebox über den halben Bildschirm.
ich mach' dir mal ein Foto

Am 11.02.2014 12:15, schrieb skienzl:

**Comment by Didi71** [comment]
![image](https://f.cloud.github.com/assets/5090129/2136274/58618f8a-930e-11e3-8be2-5cfdc408dbf0.png)
