### ISSUE TITLE
api of checkInV2-Test.php changed

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#5]
Wenn beim CheckIn ein QR-Code gelesen wird, dann sollte der QR-Code in der App nicht bewertet werden. Es sollte in der App lediglich geprüft werden, ob es sich bei dem QR-Code um einen Link handelt.

Danach wird checkInV2-Test.php aufgerufen und folgende Parameter übergeben (siehe checkInV2-Test.php)

URL: die URL des QR-Codes
params: key=checkPointId   value=13432020

damit lassen sich QR-Codes mit beliebigen URLs und Parametern erzeugen.

**Comment by skienzl** [comment]
sollte passen. aber es gibt noch kein checkInV2-Test.php für die CheckIn app :)

**Comment by Didi71** [comment]
super danke - wenn du mir die APK schickst, dann kann ich's gleich 
testen und das entsprechende checkInV2-Test.php hochladen.
ein weiterer kleiner Mosaikstein ...

Danke
Didi

Am 19.11.2013 20:13, schrieb skienzl:

**Comment by Didi71** [comment]
das mit den Parameter hatte ich anders gemeint.
params ist ein Array von key/value Paaren.

z.B.
params[0].key = "cp"
params[0].value = "13432020"
params[1].key = "rnd"
params[1].value = "36025640"

oder 

params["cp"] = "13432020";
params["rnd"] = "36025640"

**Comment by Didi71** [comment]
bitte auch die URL mitschicken, damit ich prüfen kann, ob's überhaupt der QR-Code eines unserer CheckPoints ist.

**Comment by Didi71** [comment]
wenn's für die App einfacher ist, dann gäbe es noch eine weitere Möglichkeit, indem die App ganz einfach die gesamte, gescannte URL (inkl. Parameter) dem Server übergibt. (URL - Parameter) - params, key und value wären dann gar nicht  nötig.

Dann kann ich am Server den String zerlegen, die Parameter extrahieren und die entsprechende Response zurückschicken.

Was meinst du?

**Comment by skienzl** [comment]
ist am besten so. ich schicke dir also die ganze url

**Comment by skienzl** [comment]
wie soll dann der parameter für die url heisen?

**Comment by Didi71** [comment]
URL

Am 23.11.2013 13:37, schrieb skienzl:

**Comment by skienzl** [comment]
wie machen wir das dann mit der checkpoint id? die brauche ich doch auch. wie soll ich die bestimmen wenn sich alle key namen immer ändern können

**Comment by Didi71** [comment]
die brauchst du gar nicht bestimmen. die hole ich mir am server aus der 
url raus.

Am 23.11.2013 14:49, schrieb skienzl:

**Comment by Didi71** [comment]
checkPointId können wir dann streichen.

Am 23.11.2013 14:49, schrieb skienzl:

**Comment by skienzl** [comment]
nicht wirklich. die brauchst du ja noch bei den fragen. wenn die frage richtig beantwortet wird musst du die richtig beantwortete frage auch zuweisen. oder machst du alles nur mehr über die url?

**Comment by Didi71** [comment]
die Fragen überprüft ja du in der App, und sobald sie richtig 
beantwortet wurde rufst du checkInV2.php erneut auf allerdings mit dem 
zusätzlichen Parameter: noQuestions.
Damit weiss ich, dass die Frage für diesen CheckPoint (in der URL 
enthalten) richtig beantwortet wurde - und kann das am Server 
weiterverarbeiten.

Am 23.11.2013 14:51, schrieb skienzl:

**Comment by skienzl** [comment]
das meinte ich ja nicht. aber du musst ja den checkpoint auch eindeutig zuweisen können beim 2ten aufruf wenn die fragen schon richtig beantwortet wurde. das wirst wohl über die url als ganzes machen oder? 

welche von den qr codes die du mir geschickt hast sind den aktiv geschalten? da kommt überall fehlercode 20 zurück

**Comment by Didi71** [comment]
Am 23.11.2013 15:02, schrieb skienzl:

> das meinte ich ja nicht. aber du musst ja den checkpoint auch 
> eindeutig zuweisen können beim 2ten aufruf wenn die fragen schon 
> richtig beantwortet wurde. das wirst wohl über die url als ganzes 
> machen oder?
> 
> ja!
> 
> welche von den qr codes die du mir geschickt hast sind den aktiv 
> geschalten? da kommt überall fehlercode 20 zurück
> 
> bin grad dabei am Server zwischen BIKEline und CheckIn zu unterscheiden 
> und es aufzuteilen.
> arbeite mich Schritt für Schritt weiter.

Hab' die Scripts für CheckIn nach: 
www.bikebird.at/CheckIn/TestApp-Scripts/ verschoben.
Ruf deshalb bitte die Scripts in diesem Verzeichnis auf.

Aktuell funkt. allerdings nur die Registrierung und der CheckIn.

**Comment by skienzl** [comment]
sag bescheid wenn ich die qr code scans irgendwo testen kann (bikeline oder checkin)

**Comment by Didi71** [comment]
mach ich!

Am 23.11.2013 15:14, schrieb skienzl:
