### ISSUE TITLE
Registrieren mit Foto (Nexus)

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#8]
Wenn man beim Registrieren ein Foto angibt, dann stürzt die App. manchmal ab.

Ausserdem wir das Foto beim Aktivieren weder hochgeladen noch im lokalen App-Profil gespeichert.

**Comment by skienzl** [comment]
bitte bei der nächsten version überprüfen

**Comment by Didi71** [comment]
jetzt stürzt die App ab sobald ich ein Foto aufnehme

**Comment by Didi71** [comment]
Foto wird nicht übernommen. Man kann es zwar aufnehmen, aber es wird nicht zum Server übertragen.

**Comment by skienzl** [comment]
geht der server?

**Comment by Didi71** [comment]
ja - das registrieren und der checkin sollte funktionieren.

www.bikebird.at/checkIn/TestApp-Scripts/

Am 25.11.2013 13:48, schrieb skienzl:

**Comment by skienzl** [comment]
leider nein: <br />
<b>Fatal error</b>:  require_once() [
<a href='function.require'>function.require</a>]: Failed opening required '../Base/classBIKEline.php' (include_path='.:/usr/share/pear') in 
<b>/home/.sites/228/site1541/web/CheckIn/TestApp-Scripts/uploadAvatar.php</b> on line 
<b>8</b>
<br />

**Comment by skienzl** [comment]
http://www.bikebird.at/CheckIn/TestApp-Scripts/uploadAvatar.php

**Comment by Didi71** [comment]
jetzt aber - da ist offensichtlich der letzte Sync steckengeblieben.

Am 25.11.2013 13:51, schrieb skienzl:

**Comment by skienzl** [comment]
schon probiert ob es jetzt geht mit der app?

**Comment by Didi71** [comment]
ja - gerade eben.

beim Profil bearbeiten - und Foto aufnehmen stürzt die App noch immer ab.

Am 25.11.2013 13:59, schrieb skienzl:

**Comment by skienzl** [comment]
lade gerade einen neue version auf testflight. der download der bilder + upload funktiniert. hab den crash report erweitert. bitte die app komplett löschen und dann noch einmal probieren.

**Comment by Didi71** [comment]
geht leider immer noch nicht!
Manchmal funkts - manchmal aber auch nicht.

Am 25.11.2013 14:42, schrieb skienzl:

**Comment by Didi71** [comment]
hab's grad mal mit dem Galaxy S2 versucht - passt.
Einziger Fehler ist, dass wenn ich bereits beim Registrieren ein Bild aufnehme, dann wird's nicht zum Server hochgeladen, und auch wenn ich danach auf Profil bearbeiten drücke nicht angezeigt.

versuch's gleich nochmal mit dem S3 mini.

**Comment by Didi71** [comment]
das S3 mini kackt leider auch ab.

**Comment by skienzl** [comment]
also bei dem s3 mini das ich mir gerade besorgt habe läuft alles ohne probleme.

**Comment by Didi71** [comment]
hab's auch grad nochmal probiert - bei mir ist es beim Profil bearbeiten abgestürzt

**Comment by skienzl** [comment]
kannst du dir die app runter laden und mir nach einem crash die logfiles damit schicken? 

https://play.google.com/store/apps/details?id=com.xtralogic.android.logcollector

**Comment by skienzl** [comment]
lade gerade die nächste version auf testflight. der fehler das das bild nach dem registrieren verschwand ist weg. beim anderen fehler kann ich nur raten...

**Comment by Didi71** [comment]
samsung galaxy s3 mini funktioniert jetzt, aber das nexus bleibt stecken.
es stürzt nicht ab, aber nachdem man auf den Haken drückt, verschwindet die Box mit dem Haken und nix passiert.

Man kann aber oben auf den Bikebirds drücken und gelangt dann wieder zum Hauptscreen.
