### ISSUE TITLE
Profil bearbeiten - Foto Absturz

### ISSUE THREAD

**Issue by Didi71** [Didi71/CheckIn#9]
Wenn man ein neues Profilbild aufnimmt, dann stürzt die App regelmäßig ab nachdem man den "Haken" zum Auswählen des Fotos angetippt hat.

**Comment by skienzl** [comment]
bitte bei der nächsten version überprüfen

**Comment by Didi71** [comment]
stürzt leider immer noch ab.

**Comment by skienzl** [comment]
die neue version ist ja auch noch nicht auf testflight. warte noch auf das icon und das andere kommentar zu den benachrichtigungen

**Comment by Didi71** [comment]
upps - ich dachte ... mach ich gleich

Am 25.11.2013 11:49, schrieb skienzl:
